/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2023-08-07 01:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import VO.Produtos;
import DAO.ProdutosDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.ProdutosDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("VO.Produtos");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Loja do Mainha</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <!-- CSS only -->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" \n");
      out.write("              rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("        <style>\n");
      out.write("            h1, h2 {\n");
      out.write("                text-align: center;\n");
      out.write("                font-family: Gill Sans;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            a:hover {\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <br>\n");
      out.write("        \n");
      out.write("        <nav class=\"navbar bg-body-tertiary\">\n");
      out.write("        <div class=\"container-fluid\" style=\"margin-left: 100px; margin-right: 100px;\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"ProdutosController?operacao=1\">Produtos</a>\n");
      out.write("            <form class=\"d-flex\" role=\"search\">\n");
      out.write("                 <button class=\"btn btn-outline-success\" type=\"submit\"><a href=\"login.jsp\" style=\"text-decoration: none; color:green;\" onMouseOver=\"this.style.color='white'\" onMouseOver=\"this.style.color='white'\">Login</a></button>\n");
      out.write("                 <button style=\"margin-left: 10px\" class=\"btn btn-info\" type=\"submit\"><a href=\"checkout.jsp\" style=\"text-decoration: none; color: white;\">Carrinho</a></button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        </nav>\n");
      out.write("        <hr style=\" width: 100%; \">\n");
      out.write("        \n");
      out.write("        <a type=\"hidden\" href=\"#\"></a>\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("            <h2>Listagem de Produtos </h2>\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("            ");

                ProdutosDAO pDAO = new ProdutosDAO();
                request.setAttribute("listaProduto", pDAO.buscaProdutos());
                List produtos = (List) request.getAttribute("listaProduto");
                if (produtos != null) {
                    for (int cont = 0; cont < produtos.size(); cont++) {
                    Produtos p = new Produtos();
                    p = (Produtos) produtos.get(cont);
                        out.print("<div class='row' style='margin-left: 60px'>");
                            out.print("<div class='col-sm-3'>");
                                out.print("<div class='card text-center' style='width: 18rem;'>");
                                    out.print("<div class='card-body'>");
                                    out.print("<h5 class='card-title'>" + p.getNome() + "</h5>");
                                    out.print("<p class='card-text'> R$ " + p.getValor() + "</p>");
                                    out.print("<br>");
                                    out.print("<button class='btn btn-success' type='submit'><a href='login.jsp' style='text-decoration: none; color: white;'>Adicionar ao carrinho</a></button>");
                                    out.print("</div>");
                                out.print("</div>");
                            out.print("</div>");
                        out.print("</div>");
                    }
                }
            
      out.write("\n");
      out.write("\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("            \n");
      out.write("            <br>\n");
      out.write("            <br><br>\n");
      out.write("            <br><br>\n");
      out.write("            <br><br>\n");
      out.write("            <br><br>\n");
      out.write("            <br>\n");
      out.write("            <div class=\"bg-dark text-center text-white\" style=\" width:  100%;\">\n");
      out.write("               \n");
      out.write("                <div class=\"container p-4 pb-0\" style=\"width:  100%; \">\n");
      out.write("                    <p>Gabriel Maia</p>\n");
      out.write("                    <div class=\"text-center p-3\" >\n");
      out.write("                        © 2023 Copyright:\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("            </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
