/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2023-08-07 02:05:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import VO.Produtos;
import VO.Promocao;
import java.util.List;
import java.sql.*;
import Conexao.Conexao;

public final class inserirProduto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Conexao.Conexao");
    _jspx_imports_classes.add("VO.Promocao");
    _jspx_imports_classes.add("VO.Produtos");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Inserção de Produtos novo</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <!-- CSS only -->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" \n");
      out.write("             rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

           Produtos pNovo = (Produtos) request.getAttribute("Produtos");
 
        
      out.write("<br>\n");
      out.write("        <h1 class=\"text-center\"> Inserir Produtos novo </h1>\n");
      out.write("        <br><br>\n");
      out.write("            <form class=\"container center\" name=\"frm\" method=\"post\" action=\"ProdutosController?operacao=5\" enctype=\"multipart/form-data\" style=\"margin-right: 60px;\">\n");
      out.write("                <div class=\"row mb-3\">\n");
      out.write("                  <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">Nome </label>\n");
      out.write("                  <div class=\"col-sm-5\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"nome\"  >\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-3\">\n");
      out.write("                  <label for=\"inputPassword3\" class=\"col-sm-2 col-form-label\">Valor</label>\n");
      out.write("                  <div class=\"col-sm-5\">\n");
      out.write("                    <input type=\"number\" class=\"form-control\" name=\"valor\" >\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"input-group mb-3\">\n");
      out.write("                    <label class=\"input-group-text\" for=\"inputGroupSelect01\">Promoção</label>\n");
      out.write("                    <select class=\"form-select\" id=\"inputGroupSelect01\">\n");
      out.write("                    <option selected>Escolha a promoção...</option>  \n");
      out.write("                  ");

                       PreparedStatement ps; // estrutura o sql
                        ResultSet rs; //armazenará o resultado do bd
                        Connection con; //conexão com o bd
                
                        con = new Conexao().conectar();
                        String sql = "SELECT id_promocao, nome_promocao FROM promocao;";
                        ps = con.prepareStatement(sql);
                        rs = ps.executeQuery();
                        
                        Promocao promo = new Promocao();
                        while(rs.next()){
                            out.print("<option name='id_promocao' value='" + rs.getInt(1) + "'> " + rs.getString(2) + "</option>");
                        }
                   
      out.write("</select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("                Inserir\n");
      out.write("            </button>\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-primary\">\n");
      out.write("                        <a style=\"text-decoration:none; color: black \"href=\"produtos.html\">\n");
      out.write("                            Voltar\n");
      out.write("                        </a>\n");
      out.write("            </button>   \n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
