/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2023-08-07 13:52:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Conexao.Conexao;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Conexao.Conexao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\" data-bs-theme=\"auto\">\n");
      out.write("  <head><script src=\"../assets/js/color-modes.js\"></script>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.115.4\">\n");
      out.write("    <title>Login</title>\n");
      out.write("\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" \n");
      out.write("              rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("      .bd-placeholder-img {\n");
      out.write("        font-size: 1.125rem;\n");
      out.write("        text-anchor: middle;\n");
      out.write("        -webkit-user-select: none;\n");
      out.write("        -moz-user-select: none;\n");
      out.write("        user-select: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @media (min-width: 768px) {\n");
      out.write("        .bd-placeholder-img-lg {\n");
      out.write("          font-size: 3.5rem;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .b-example-divider {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 3rem;\n");
      out.write("        background-color: rgba(0, 0, 0, .1);\n");
      out.write("        border: solid rgba(0, 0, 0, .15);\n");
      out.write("        border-width: 1px 0;\n");
      out.write("        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .b-example-vr {\n");
      out.write("        flex-shrink: 0;\n");
      out.write("        width: 1.5rem;\n");
      out.write("        height: 100vh;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .bi {\n");
      out.write("        vertical-align: -.125em;\n");
      out.write("        fill: currentColor;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .nav-scroller {\n");
      out.write("        position: relative;\n");
      out.write("        z-index: 2;\n");
      out.write("        height: 2.75rem;\n");
      out.write("        overflow-y: hidden;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .nav-scroller .nav {\n");
      out.write("        display: flex;\n");
      out.write("        flex-wrap: nowrap;\n");
      out.write("        padding-bottom: 1rem;\n");
      out.write("        margin-top: -1px;\n");
      out.write("        overflow-x: auto;\n");
      out.write("        text-align: center;\n");
      out.write("        white-space: nowrap;\n");
      out.write("        -webkit-overflow-scrolling: touch;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .btn-bd-primary {\n");
      out.write("        --bd-violet-bg: #712cf9;\n");
      out.write("        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;\n");
      out.write("\n");
      out.write("        --bs-btn-font-weight: 600;\n");
      out.write("        --bs-btn-color: var(--bs-white);\n");
      out.write("        --bs-btn-bg: var(--bd-violet-bg);\n");
      out.write("        --bs-btn-border-color: var(--bd-violet-bg);\n");
      out.write("        --bs-btn-hover-color: var(--bs-white);\n");
      out.write("        --bs-btn-hover-bg: #6528e0;\n");
      out.write("        --bs-btn-hover-border-color: #6528e0;\n");
      out.write("        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);\n");
      out.write("        --bs-btn-active-color: var(--bs-btn-hover-color);\n");
      out.write("        --bs-btn-active-bg: #5a23c8;\n");
      out.write("        --bs-btn-active-border-color: #5a23c8;\n");
      out.write("      }\n");
      out.write("      .bd-mode-toggle {\n");
      out.write("        z-index: 1500;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      html,\n");
      out.write("        body {\n");
      out.write("          height: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-signin {\n");
      out.write("          max-width: 330px;\n");
      out.write("          padding: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-signin .form-floating:focus-within {\n");
      out.write("          z-index: 2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-signin input[type=\"email\"] {\n");
      out.write("          margin-bottom: -1px;\n");
      out.write("          border-bottom-right-radius: 0;\n");
      out.write("          border-bottom-left-radius: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-signin input[type=\"password\"] {\n");
      out.write("          margin-bottom: 10px;\n");
      out.write("          border-top-left-radius: 0;\n");
      out.write("          border-top-right-radius: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #erro {\n");
      out.write("            width: 80%;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            border: 1px solid red;\n");
      out.write("            background-color: beige;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("  </head>\n");
      out.write("  <body class=\"d-flex align-items-center py-4 bg-body-tertiary\">\n");
      out.write("      \n");
      out.write("      \n");
      out.write("        <main class=\"form-signin w-100 m-auto\">\n");
      out.write("            <form method=\"post\" action=\"autenticar.jsp\">\n");
      out.write("            <h1 class=\"h3 mb-3 fw-normal\">Please sign in</h1>\n");
      out.write("\n");
      out.write("            <div class=\"form-floating\">\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"floatingInput\" placeholder=\"name@example.com\" name=\"login\" required>\n");
      out.write("              <label for=\"floatingInput\">Login</label>\n");
      out.write("            </div><br>\n");
      out.write("            <div class=\"form-floating\">\n");
      out.write("              <input type=\"password\" class=\"form-control\" id=\"floatingPassword\" placeholder=\"Password\" name=\"senha\" required>\n");
      out.write("              <label for=\"floatingPassword\">Password</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-check text-start my-3\">\n");
      out.write("              <input class=\"form-check-input\" type=\"checkbox\" value=\"remember-me\" id=\"flexCheckDefault\">\n");
      out.write("              <label class=\"form-check-label\" for=\"flexCheckDefault\">\n");
      out.write("                Remember me\n");
      out.write("              </label>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("                    <button class=\"btn btn-primary w-100 py-2\" type=\"submit\" >Login</button>\n");
      out.write("            <p class=\"mt-5 mb-3 text-body-secondary\">Â© 2023 Copyright</p>\n");
      out.write("          </form>\n");
      out.write("        </main>\n");
      out.write("    <script src=\"../assets/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
