/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2023-08-08 03:02:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import VO.Produtos;
import DAO.ProdutosDAO;
import VO.Carrinho;
import DAO.CarrinhoDAO;
import java.sql.*;
import Conexao.Conexao;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.ProdutosDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Conexao.Conexao");
    _jspx_imports_classes.add("VO.Carrinho");
    _jspx_imports_classes.add("DAO.CarrinhoDAO");
    _jspx_imports_classes.add("VO.Produtos");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\" data-bs-theme=\"auto\">\n");
      out.write("  <head><script src=\"../assets/js/color-modes.js\"></script>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.115.4\">\n");
      out.write("    <title>Checkout </title>\n");
      out.write("\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" \n");
      out.write("              rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("      .bd-placeholder-img {\n");
      out.write("        font-size: 1.125rem;\n");
      out.write("        text-anchor: middle;\n");
      out.write("        -webkit-user-select: none;\n");
      out.write("        -moz-user-select: none;\n");
      out.write("        user-select: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @media (min-width: 768px) {\n");
      out.write("        .bd-placeholder-img-lg {\n");
      out.write("          font-size: 3.5rem;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .b-example-divider {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 3rem;\n");
      out.write("        background-color: rgba(0, 0, 0, .1);\n");
      out.write("        border: solid rgba(0, 0, 0, .15);\n");
      out.write("        border-width: 1px 0;\n");
      out.write("        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .b-example-vr {\n");
      out.write("        flex-shrink: 0;\n");
      out.write("        width: 1.5rem;\n");
      out.write("        height: 100vh;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .bi {\n");
      out.write("        vertical-align: -.125em;\n");
      out.write("        fill: currentColor;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .nav-scroller {\n");
      out.write("        position: relative;\n");
      out.write("        z-index: 2;\n");
      out.write("        height: 2.75rem;\n");
      out.write("        overflow-y: hidden;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .nav-scroller .nav {\n");
      out.write("        display: flex;\n");
      out.write("        flex-wrap: nowrap;\n");
      out.write("        padding-bottom: 1rem;\n");
      out.write("        margin-top: -1px;\n");
      out.write("        overflow-x: auto;\n");
      out.write("        text-align: center;\n");
      out.write("        white-space: nowrap;\n");
      out.write("        -webkit-overflow-scrolling: touch;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .btn-bd-primary {\n");
      out.write("        --bd-violet-bg: #712cf9;\n");
      out.write("        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;\n");
      out.write("\n");
      out.write("        --bs-btn-font-weight: 600;\n");
      out.write("        --bs-btn-color: var(--bs-white);\n");
      out.write("        --bs-btn-bg: var(--bd-violet-bg);\n");
      out.write("        --bs-btn-border-color: var(--bd-violet-bg);\n");
      out.write("        --bs-btn-hover-color: var(--bs-white);\n");
      out.write("        --bs-btn-hover-bg: #6528e0;\n");
      out.write("        --bs-btn-hover-border-color: #6528e0;\n");
      out.write("        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);\n");
      out.write("        --bs-btn-active-color: var(--bs-btn-hover-color);\n");
      out.write("        --bs-btn-active-bg: #5a23c8;\n");
      out.write("        --bs-btn-active-border-color: #5a23c8;\n");
      out.write("      }\n");
      out.write("      .bd-mode-toggle {\n");
      out.write("        z-index: 1500;\n");
      out.write("      }\n");
      out.write("      .container {\n");
      out.write("        max-width: 960px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("    <link href=\"checkout.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("  <body class=\"bg-body-tertiary\">\n");
      out.write("\n");
      out.write("    \n");
      out.write("<div class=\"container\">\n");
      out.write("  <main>\n");
      out.write("    <div class=\"py-5 text-center\">\n");
      out.write("      <h2>Checkout form</h2></div>\n");
      out.write("\n");
      out.write("    <div class=\"row g-5\">\n");
      out.write("      <div class=\"col-md-5 col-lg-4 order-md-last\">\n");
      out.write("        <h4 class=\"d-flex justify-content-between align-items-center mb-3\">\n");
      out.write("          <span class=\"text-primary\">Carrinho</span>\n");
      out.write("          ");

              CarrinhoDAO carDAO = new CarrinhoDAO();
              PreparedStatement ps; // estrutura o sql
                ResultSet rs; //armazenará o resultado do bd
                Connection con; //conexão com o bd

                con = new Conexao().conectar();
                
                String sql = "SELECT id_carrinho, produto.id_produto, id_cliente, itens_qtd, valor_total FROM carrinho INNER JOIN produto ON produto.id_produto = carrinho.id_produto";
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                
              request.setAttribute("listaItensCarrinho", carDAO.buscaItensCarrinho());
              List carrinho = (List) request.getAttribute("listaItensCarrinho");
              
              out.print("<span class='badge bg-primary rounded-pill'>"+ carrinho.size() +"</span>");
              out.print("<h4>");
              Carrinho carr = new Carrinho();
                    for (int cont = 0; cont < carrinho.size(); cont++) {
                        
                        carr = (Carrinho) carrinho.get(cont);
                        Produtos p = new Produtos();
                        p.setIdProduto(carr.getId_produto());
                        out.print("<ul class='list-group mb-3'>");
                            out.print("<li class='list-group-item d-flex justify-content-between lh-sm'>");
                                out.print("<div>");
                                    out.print("<h6 class='my-0'>Nome Produto</h6>");
                                    out.print("<small class='text-body-secondary'>"+ carr.getProdutoNome() +"</small>");
                                out.print("</div>");
                                out.print("<span class='text-body-secondary'>R$  QTD.</span>");
                                out.print("<span class='text-body-secondary'> " + carr.getProdutoValor() + " "+carr.getItens_qtd() +"</span>");
                            out.print("</li>");
                }
              out.print("</h4>");
              out.print("<li class='list-group-item d-flex justify-content-between'>");
              Double somaTotal = 0.0;
                  while(rs.next()){
                    somaTotal += carr.getValorTotalCarrinho();
                  }
              out.print("<span> Total R$ " + somaTotal + "</span>");
          
      out.write("\n");
      out.write("<!--        </h4>\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between\">-->\n");
      out.write("              \n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-7 col-lg-8\">\n");
      out.write("        <h4 class=\"mb-3\">Endereço</h4>\n");
      out.write("        <form class=\"needs-validation\" name=\"frm\" method=\"post\" action=\"CarrinhoController?operacao=2\" enctype=\"multipart/form-data\" novalidate>\n");
      out.write("            <div class=\"row g-3\">\n");
      out.write("            <div class=\"col-sm-6\">\n");
      out.write("              <label for=\"firstName\" class=\"form-label\">Primeiro nome</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"firstName\" placeholder=\"\" value=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Primeiro nome é requerido.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-sm-6\">\n");
      out.write("              <label for=\"lastName\" class=\"form-label\">Ultimo nome</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"lastName\" placeholder=\"\" value=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Ultimo nome é requerido.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"username\" class=\"form-label\">Login</label>\n");
      out.write("              <div class=\"input-group has-validation\">\n");
      out.write("                <span class=\"input-group-text\">@</span>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"username\" placeholder=\"Username\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                  Seu usuario érequerido.\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"email\" class=\"form-label\">Email <span class=\"text-body-secondary\">(Opcional)</span></label>\n");
      out.write("              <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"email@example.com\">\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Coloque o email para que você receba feedback.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"address\" class=\"form-label\">Endereço</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"Rua teste, 255\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Coloque o endereço, por favor.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"address2\" class=\"form-label\">Complemento <span class=\"text-body-secondary\">(Opcional)</span></label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"address2\" placeholder=\"Complemento\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-5\">\n");
      out.write("              <label for=\"country\" class=\"form-label\">Pais</label>\n");
      out.write("              <select class=\"form-select\" id=\"country\" >\n");
      out.write("                <option value=\"\">Escolha...</option>\n");
      out.write("                <option>Brasil</option>\n");
      out.write("              </select>\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Escolha um pais.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("              <label for=\"state\" class=\"form-label\">Estado</label>\n");
      out.write("              <select class=\"form-select\" id=\"state\" >\n");
      out.write("                <option value=\"\">Escolha...</option>\n");
      out.write("                <option>São Paulo</option>\n");
      out.write("                <option>Belo Horizonte</option>\n");
      out.write("                <option>Mato Grosso </option>\n");
      out.write("                <option>Rio de Janeiro</option>\n");
      out.write("                <option>Mato Grosso do Sul</option>\n");
      out.write("              </select>\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Escolha um estado valido.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("              <label for=\"zip\" class=\"form-label\">CEP</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"zip\" placeholder=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                CEP é requerido.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <hr class=\"my-4\">\n");
      out.write("\n");
      out.write("          <div class=\"form-check\">\n");
      out.write("            <input type=\"checkbox\" class=\"form-check-input\" id=\"save-info\">\n");
      out.write("            <label class=\"form-check-label\" for=\"save-info\">Salvar as informações para proxima compra</label>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <hr class=\"my-4\">\n");
      out.write("\n");
      out.write("          <h4 class=\"mb-3\">Pagamento</h4>\n");
      out.write("\n");
      out.write("          <div class=\"my-3\">\n");
      out.write("            <div class=\"form-check\">\n");
      out.write("              <input id=\"credit\" name=\"paymentMethod\" type=\"radio\" class=\"form-check-input\" checked >\n");
      out.write("              <label class=\"form-check-label\" for=\"credit\">Cartão de Credito</label>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-check\">\n");
      out.write("              <input id=\"debit\" name=\"paymentMethod\" type=\"radio\" class=\"form-check-input\" >\n");
      out.write("              <label class=\"form-check-label\" for=\"debit\">Cartão de Debito</label>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-check\">\n");
      out.write("              <input id=\"paypal\" name=\"paymentMethod\" type=\"radio\" class=\"form-check-input\" >\n");
      out.write("              <label class=\"form-check-label\" for=\"paypal\">Pix</label>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"row gy-3\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("              <label for=\"cc-name\" class=\"form-label\">Nome no cartão</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"cc-name\" placeholder=\"\" >\n");
      out.write("              <small class=\"text-body-secondary\">Nome completo impresso no cartão</small>\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Nome no cartão é requerido.\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("              <label for=\"cc-number\" class=\"form-label\">Numero do cartão</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"cc-number\" placeholder=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                Numero do cartão é requerido\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("              <label for=\"cc-expiration\" class=\"form-label\">Validade</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"cc-expiration\" placeholder=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                  Data de validade é requerida\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("              <label for=\"cc-cvv\" class=\"form-label\">CVV</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"cc-cvv\" placeholder=\"\" >\n");
      out.write("              <div class=\"invalid-feedback\">\n");
      out.write("                CVV é requerido\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <hr class=\"my-4\">\n");
      out.write("\n");
      out.write("          <button class=\"w-100 btn btn-primary btn-lg\" type=\"submit\">Continue para finalizar compra</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("\n");
      out.write("  <footer class=\"my-5 pt-5 text-body-secondary text-center text-small\">\n");
      out.write("    <p class=\"mb-1\">Â© 2023 Copyright</p>\n");
      out.write("  </footer>\n");
      out.write("</div>\n");
      out.write("<script src=\"../assets/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"src/checkout.js\"></script></body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
